name: 🌈 Export All
on: [push, pull_request, workflow_dispatch]

env:
  GODOT_VERSION: '3.4.4'

jobs:
  # Hacky workaround to use variables in container image
  # https://github.community/t/how-to-use-env-with-container-image/17252/25
  set-env:
    name: Set environment
    runs-on: ubuntu-20.04
    outputs:
      godot-version: ${{ steps.set-gd-ver.outputs.godot-version }}
    steps:
      - id: set-gd-ver
        run: echo "::set-output name=godot-version::${{ env.GODOT_VERSION }}"

  export:
    name: ${{ matrix.job-name }}
    needs: set-env
    runs-on: ubuntu-20.04

    container:
      image: barichello/godot-ci:${{ needs.set-env.outputs.godot-version }}
    
    strategy:
      matrix:
        include:
          - platform: windows
            job-name: "🪟 Windows build"
          - platform: osx
            job-name: "🍎 macOS build"
          - platform: linux
            job-name: "🐧 Linux build"
          - platform: web
            job-name: "🖐️ HTML5 build"

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v3

      - name: Setup export templates
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable

      - name: Export
        run: |
          python export.py ${{ matrix.platform }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}
          path: bin/${{ matrix.platform }}